FROM ubuntu:20.04

# get time-zone
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# get user
RUN useradd -m fuzz

# get minimum Dependencies for scripts
RUN apt-get -y update
#RUN apt-get -y apt-utils
RUN apt-get -y install git
RUN apt-get -y install build-essential
RUN apt-get -y install jq
RUN apt-get -y install python3
# get Dependencies from file for fuzzer and program
ADD dockerDependencies /
RUN apt-get -y update && apt-get -y install $(cat /dockerDependencies)


USER fuzz
WORKDIR /home/fuzz/

ADD scriptsInDocker/ /home/fuzz/
CMD "ls"

ADD initFuzzer.json /home/fuzz
ADD initProgram.json /home/fuzz

RUN ls
CMD "ls"

# install Fuzzer
#ADD initFuzzer.json /home/fuzz
#ADD installFuzzer.sh /home/fuzz
#RUN /home/fuzz/installFuzzer.sh

# install CVE_program
#ADD initProgram.json /home/fuzz
#ADD installProgram.sh /home/fuzz
#RUN /home/fuzz/installProgram.sh

# add CVE_input
#ADD downloadInputFiles.sh /home/fuzz
#RUN /home/fuzz/downloadInputFiles.sh

CMD "/bin/sh"
CMD "/home/fuzz/runInDocker.sh"
